Repository daily-emotion/front-end, pull requests merged in 2025-01, with the labels that each got.

#3 Feat/Full-Calendar 이용한 캘린더 구현
  .env
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/Daily-Emotion-Logo.png
  src/assets/react.svg
  src/components/calendar/Calendar.tsx
  src/components/calendar/CreateDiaryButton.tsx
  src/components/calendar/EmotionIcon.tsx
  src/components/report/Chart.tsx
  src/components/report/Report.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/services/api.tsx
  src/styles/components/calendar/Calendar.css
  src/styles/pages/LoginPage.css
Labels: ✨ feat, 🎨 ui/ux

#7 Feat/일기 작성/조회/수정에 필요한 Data 상태 관리 구현
  src/stores/diaryStores.tsx
Labels: ✨ feat

#11 Chore/이슈, PR 템플릿
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/maintenance_issue.md
  .github/pull_request_template.md
Labels: 🔧 chore, 📝 docs

#9 Feat/일기와 관련된 CRUD 작업을 처리하는 API 호출 함수
  jest.config.js
  package-lock.json
  package.json
  src/config/jest.config.js
  src/services/diary/DiaryService.tsx
  src/services/diary/diaryService.test.tsx
  tsconfig.json
Labels: ✨ feat

#14 Feature/서버로부터 일기 데이터를 받아와 일기를 보여주는 기능 구현
  src/App.tsx
  src/pages/viewDiaryPage.tsx
  src/services/diary/DiaryService.tsx
Labels: ✨ feat, 🎨 ui/ux

#16 Feat/일기 수정 기능 구현
  src/pages/updateDiary.tsx
Labels: ✨ feat

#19 [FIX] createDiary API 호출에서 필요한 인수 추가 및 페이지 라우팅 경로 지정
  src/App.tsx
  src/pages/updateDiary.tsx
  src/services/diary/DiaryService.tsx
Labels: 🐛 fix

#24 [MAINTENACE] 감정 표현 상수를 배열에서 객체로 수정하여 보여지는 값(UI)은 key 값으로 서버에 전달되는 값은 value 값으로 설정
  .gitignore
  src/components/diary/emotionSelectorModal.tsx
  src/contants/emtionsContants.tsx
  src/pages/createDiary.tsx
Labels: ♻️ refactor, 🎨 ui/ux
