Repository daily-emotion/front-end, pull requests merged in 2025-02, with the labels that each got.

#27 [FIX] API headers에 토큰 추가 및 라우팅 경로 수정
  src/App.tsx
  src/pages/viewDiaryPage.tsx
  src/services/diary/DiaryService.tsx
Labels: ♻️ refactor, 🐛 fix

#26 Feat/statistics main page
  src/App.tsx
  src/components/calendar/Calendar.tsx
  src/components/calendar/Calendar2.tsx
  src/components/calendar/CreateDiaryButton.tsx
  src/components/calendar/EmotionIcon.tsx
  src/components/common/Header.tsx
  src/components/report/Chart.tsx
  src/components/report/MonthlyChart.tsx
  src/configs/apiConfig.tsx
  src/configs/jest.config.js
  src/pages/MainPage.tsx
  src/pages/MainPage2.tsx
  src/pages/createDiary.tsx
  src/services/api.tsx
  src/services/auth/AuthService.tsx
  src/services/auth/tokenService.tsx
  src/services/diary/DiaryService.tsx
  src/services/diary/diaryService.test.tsx
Labels: ✨ feat, 🐛 fix

#28 [FEATRUE] 이미지 첨부 관련 API 생성 및 다른 API 관리
  src/pages/createDiary.tsx
  src/pages/viewDiaryPage.tsx
  src/services/diary/DiaryService.tsx
Labels: ✨ feat, ♻️ refactor, 🐛 fix

#33 [REFACTOR] 서버에 imageUrl 값을 전달 및 태그에 관련된 400 error 수정
  src/pages/createDiary.tsx
  src/pages/viewDiaryPage.tsx
  src/services/diary/DiaryService.tsx
Labels: ♻️ refactor, 🐛 fix

#39 [FEATURE] image 확장자 제한 및 이미지 1개 업로드로 제한
  src/App.tsx
  src/components/diary/addImage.tsx
  src/pages/createDiary.tsx
Labels: ✨ feat, ♻️ refactor, 🎨 ui/ux

#40 [FEATURE] 조회페이지에 이미지 구현 및 수정페이지에서 감정표현 및 이미지 불러오기
  src/App.tsx
  src/components/diary/tagSelectorModal.tsx
  src/pages/createDiary.tsx
  src/pages/updateDiary.tsx
  src/pages/viewDiaryPage.tsx
  src/services/diary/DiaryService.tsx
Labels: ✨ feat, ♻️ refactor

#42 [Refactor] 수정 페이지에서 태그 수정 후 조회페이지로 이동 시 수정된 태그 반영 안되는 오류 발생
  src/App.tsx
  src/pages/updateDiary.tsx
  src/pages/viewDiaryPage.tsx
  src/services/diary/DiaryService.tsx
Labels: ♻️ refactor, 🐛 fix

#44 [UX/UI] Main Header 수정
  src/App.css
  src/App.tsx
  src/assets/images/logo/Daily-Emotion-Logo.png
  src/assets/images/logo/emampleLogo.png
  src/assets/images/logo/mainLogo.png
  src/components/common/Header.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/createDiary.tsx
  src/styles/common/common.css
  src/styles/common/header.css
Labels: ♻️ refactor, 🎨 ui/ux

#45 [FIX] 로그인 안되는 오류 수정
  src/App.tsx
  src/components/common/Header.tsx
Labels: 🐛 fix

#46 UI : tag 앞에 # 추가
  src/pages/createDiary.tsx
  src/pages/viewDiaryPage.tsx
Labels: 🎨 ui/ux

#49 [FIX] 통계 페이지 UI 요소 수정
  src/components/report/Report.tsx
  src/pages/ReportPage.tsx
Labels: 🐛 fix, 🎨 ui/ux

#50 UI / 일기 생성 페이지 UI 수정
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/backImage/background-Image.png
  src/assets/images/diary/diary_icon1.png
  src/assets/images/diary/diary_icon2.png
  src/assets/images/diary/diary_icon3.png
  src/components/common/Header.tsx
  src/components/diary/addImage.tsx
  src/components/diary/emotionSelectorModal.tsx
  src/pages/createDiary.tsx
  src/services/auth/tokenService.tsx
  src/services/diary/DiaryService.tsx
  src/styles/Modal/EmotionModal.css
  src/styles/pages/DiaryPage.css
Labels: ♻️ refactor, 🎨 ui/ux

#51 fix : 시스템이 다크모드 일 경우 무시할 수 있도록 수정
  index.html
  src/App.css
  src/components/common/Header.tsx
  src/index.css
  src/pages/MainPage.tsx
  src/styles/common/header.css
  src/styles/pages/DiaryPage.css
Labels: 🎨 ui/ux

#52 [UX&UI] 일기 생성 페이지 UI 수정 및 일기 조회 페이지 UI 구현
  src/App.tsx
  src/pages/viewDiaryPage.tsx
  src/styles/pages/DiaryPage.css
  src/styles/pages/ViewDiaryPage.css
Labels: 🎨 ui/ux

#53 [UX&UI] 일기 수정 페이지 UI 수정
  src/pages/createDiary.tsx
  src/pages/updateDiary.tsx
  src/styles/pages/DiaryPage.css
Labels: ♻️ refactor, 🎨 ui/ux
